services:
  warp:
    image: ghcr.io/lengyuesky/hysteria2-over-warp:latest
    container_name: warp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      CAMPUS_LOGIN_SCRIPT: /config/scripts/campus-login.sh
      HY2_PASSWORD: change-this-password
    volumes:
      - ./config/scripts:/config/scripts:ro
      - ./config/hysteria:/config/hysteria
    ports:
      - 8443:8443/udp
    stdin_open: true
    tty: true
    networks:
      - warp_macvlan

networks:
  warp_macvlan:
    external: true
    name: warp_macvlan
