services:
  warp:
    image: ghcr.io/lengyuesky/hysteria2-over-warp:latest
    container_name: warp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    stdin_open: true
    tty: true
    networks:
      - warp_macvlan

networks:
  warp_macvlan:
    external: true
    name: warp_macvlan
